#options can and should be changed ingame

[game_options]
    fullscreen = false
    key_set = 'wasd'
    fps = 0

    [keys.wasd]
        key_north = "w"
        key_east = "d"
        key_south = "s"
        key_west = "a"
        key_inventory = "i"
        key_pickups = "e"
        key_equip = "z"
        key_help = "?"
        key_drop = "f"
        key_character = "c"
        key_char_stat = "x"

    [keys.arrows]
        key_north = "KEY_UP"
        key_east = "KEY_RIGHT"
        key_south = "KEY_DOWN"
        key_west = "KEY_LEFT"
        key_inventory = "i"
        key_pickups = "e"
        key_equip = "z"
        key_help = "?"
        key_drop = "f"
        key_character = "c"

