# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _cEngine
else:
    import _cEngine

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class gEngine(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, w, h, name, fs, fps, font):
        _cEngine.gEngine_swiginit(self, _cEngine.new_gEngine(w, h, name, fs, fps, font))

    def mClear(self, c):
        return _cEngine.gEngine_mClear(self, c)

    def mAddConsole(self, w, h):
        return _cEngine.gEngine_mAddConsole(self, w, h)

    def mDestroyConsole(self, c):
        return _cEngine.gEngine_mDestroyConsole(self, c)

    def mBlit(self, *args):
        return _cEngine.gEngine_mBlit(self, *args)

    def mFlush(self):
        return _cEngine.gEngine_mFlush(self)

    def mGetMouseCX(self):
        return _cEngine.gEngine_mGetMouseCX(self)

    def mGetMouseCY(self):
        return _cEngine.gEngine_mGetMouseCY(self)

    def mSysGetFPS(self):
        return _cEngine.gEngine_mSysGetFPS(self)

    def mSetForegroundColor(self, c, h, s, v):
        return _cEngine.gEngine_mSetForegroundColor(self, c, h, s, v)

    def mSetBackgroundColor(self, c, h, s, v):
        return _cEngine.gEngine_mSetBackgroundColor(self, c, h, s, v)

    def mSetCharBackground(self, c, x, y, r, g, b, flag):
        return _cEngine.gEngine_mSetCharBackground(self, c, x, y, r, g, b, flag)

    def mSetCharForeground(self, c, x, y, r, g, b):
        return _cEngine.gEngine_mSetCharForeground(self, c, x, y, r, g, b)

    def mPutCharEx(self, con, x, y, c, fr, fg, fb, br, bg, bb):
        return _cEngine.gEngine_mPutCharEx(self, con, x, y, c, fr, fg, fb, br, bg, bb)

    def mPutChar(self, con, x, y, c, flag):
        return _cEngine.gEngine_mPutChar(self, con, x, y, c, flag)

    def mSetChar(self, con, x, y, c):
        return _cEngine.gEngine_mSetChar(self, con, x, y, c)

    def mSetAlignment(self, c, flag):
        return _cEngine.gEngine_mSetAlignment(self, c, flag)

    def mPrint(self, c, x, y, fmt):
        return _cEngine.gEngine_mPrint(self, c, x, y, fmt)

    def mPrintEx(self, c, x, y, bk, al, fmt):
        return _cEngine.gEngine_mPrintEx(self, c, x, y, bk, al, fmt)

    def mPrintRect(self, c, x, y, w, h, fmt):
        return _cEngine.gEngine_mPrintRect(self, c, x, y, w, h, fmt)

    def mPrintRectEx(self, c, x, y, w, h, bk, al, fmt):
        return _cEngine.gEngine_mPrintRectEx(self, c, x, y, w, h, bk, al, fmt)

    def mGetHeightRect(self, c, x, y, w, h, fmt):
        return _cEngine.gEngine_mGetHeightRect(self, c, x, y, w, h, fmt)

    def mPrintFrame(self, c, x, y, w, h, clear, f, fmt):
        return _cEngine.gEngine_mPrintFrame(self, c, x, y, w, h, clear, f, fmt)

    def mCreateImage(self, w, h):
        return _cEngine.gEngine_mCreateImage(self, w, h)

    def mDestroyImage(self, i):
        return _cEngine.gEngine_mDestroyImage(self, i)

    def mLoadImage(self, filename):
        return _cEngine.gEngine_mLoadImage(self, filename)

    def mImageGetHeight(self, i):
        return _cEngine.gEngine_mImageGetHeight(self, i)

    def mImageGetWidth(self, i):
        return _cEngine.gEngine_mImageGetWidth(self, i)

    def mImageGetR(self, i, x, y):
        return _cEngine.gEngine_mImageGetR(self, i, x, y)

    def mImageGetG(self, i, x, y):
        return _cEngine.gEngine_mImageGetG(self, i, x, y)

    def mImageGetB(self, i, x, y):
        return _cEngine.gEngine_mImageGetB(self, i, x, y)

    def mImageClear(self, i, r=0, g=0, b=0):
        return _cEngine.gEngine_mImageClear(self, i, r, g, b)

    def mImagePutPixel(self, i, x, y, r, g, b):
        return _cEngine.gEngine_mImagePutPixel(self, i, x, y, r, g, b)

    def mImageScale(self, i, newWidth, newHeight):
        return _cEngine.gEngine_mImageScale(self, i, newWidth, newHeight)

    def mImageHFlip(self, i):
        return _cEngine.gEngine_mImageHFlip(self, i)

    def mImageVFlip(self, i):
        return _cEngine.gEngine_mImageVFlip(self, i)

    def mImageBlitRect(self, i, c, x, y, w=-1, h=-1, flag=1):
        return _cEngine.gEngine_mImageBlitRect(self, i, c, x, y, w, h, flag)

    def mImageBlit(self, i, c, x, y, flag=1, sx=1.0, sy=1.0, angle=0.0):
        return _cEngine.gEngine_mImageBlit(self, i, c, x, y, flag, sx, sy, angle)

    def mImageBlit2x(self, i, c, x, y, sx=0, sy=0, w=-1, h=-1):
        return _cEngine.gEngine_mImageBlit2x(self, i, c, x, y, sx, sy, w, h)

    def mDungeonNewMap(self, w, h):
        return _cEngine.gEngine_mDungeonNewMap(self, w, h)

    def mDungeonReset(self):
        return _cEngine.gEngine_mDungeonReset(self)

    def mDungeonAddTile(self, x, y, blocked, blockSight, r, g, b):
        return _cEngine.gEngine_mDungeonAddTile(self, x, y, blocked, blockSight, r, g, b)

    def mDungeonRenderStaticMap(self, con, x, y):
        return _cEngine.gEngine_mDungeonRenderStaticMap(self, con, x, y)

    def mDungeonRenderStaticMap2x(self, con, x, y):
        return _cEngine.gEngine_mDungeonRenderStaticMap2x(self, con, x, y)

    def mDungeonRenderScrollingMap(self, c, x, y):
        return _cEngine.gEngine_mDungeonRenderScrollingMap(self, c, x, y)

    def mDungeonRenderScrollingMap2x(self, c, x, y):
        return _cEngine.gEngine_mDungeonRenderScrollingMap2x(self, c, x, y)

    def mDungeonIsExplored(self, x, y):
        return _cEngine.gEngine_mDungeonIsExplored(self, x, y)

    def mLightmaskInit(self, w, h):
        return _cEngine.gEngine_mLightmaskInit(self, w, h)

    def mLightmaskSetAmbient(self, ambient):
        return _cEngine.gEngine_mLightmaskSetAmbient(self, ambient)

    def mLightmaskCalculateLight(self, light):
        return _cEngine.gEngine_mLightmaskCalculateLight(self, light)

    def mLightmaskCompute(self):
        return _cEngine.gEngine_mLightmaskCompute(self)

    def mLightmaskLightTile(self, x, y, amount, light):
        return _cEngine.gEngine_mLightmaskLightTile(self, x, y, amount, light)

    def mLightmaskAddLight(self, x, y, r, g, b, intensity=1.0, radius=20.5):
        return _cEngine.gEngine_mLightmaskAddLight(self, x, y, r, g, b, intensity, radius)

    def mLightmaskGetValueR(self, x, y):
        return _cEngine.gEngine_mLightmaskGetValueR(self, x, y)

    def mLightmaskGetValueG(self, x, y):
        return _cEngine.gEngine_mLightmaskGetValueG(self, x, y)

    def mLightmaskGetValueB(self, x, y):
        return _cEngine.gEngine_mLightmaskGetValueB(self, x, y)

    def mLightmaskInCircle(self, cx, cy, tx, ty, radius):
        return _cEngine.gEngine_mLightmaskInCircle(self, cx, cy, tx, ty, radius)

    def mLightmaskDistanceFromCenter(self, cx, cy, tx, ty, radius):
        return _cEngine.gEngine_mLightmaskDistanceFromCenter(self, cx, cy, tx, ty, radius)

    def mLightmaskReset(self):
        return _cEngine.gEngine_mLightmaskReset(self)
    __swig_destroy__ = _cEngine.delete_gEngine

# Register gEngine in _cEngine:
_cEngine.gEngine_swigregister(gEngine)



