#DO NOT CHANGE THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
[engine_config]
screen_width = 80
screen_height = 55 
#font = 'terminal10x10_gs_tc.png'
font = 'dejavu_wide16x16_gs_tc.png'
name = 'Ascension: The Lost Horizon'
version = '0.0.1b'
font_layout = 8 #TCOD layout
font_type = 4 #GREYSCALE type

[tile_colors] # set up a dict or something with colors
