
#/*===============================================
#                Base Armor
#===============================================*/
[["armor"]]
    name = "plate"
    cell = 'torso'
    type = "armor"
    location = "Torso"
    base_value = 75
    description = "Hard to eat off of"
    threat_level = 0.5
    allowed_materials = 3 #1 for cloth, 2 for metal, 3 for both
    bonus = 3
    penalty = 3

[["armor"]]
    name = "plate helm"
    cell = 'helm'
    type = "armor"
    location = "Head"
    base_value = 50
    description = "Low visibility"
    threat_level = 0.5
    allowed_materials = 3 #1 for cloth, 2 for metal, 3 for both
    bonus = 1
    penalty = 1

[["armor"]]
    name = "plate gloves"
    cell = 'glove'
    type = "armor"
    location = "Hands"
    base_value = 75
    description = "Hard to eat off of"
    threat_level = 0.5
    allowed_materials = 3 #1 for cloth, 2 for metal, 3 for both
    bonus = 3
    penalty = 3

[["armor"]]
    name = "plate greaves"
    cell = 'boots'
    type = "armor"
    location = "Legs"
    base_value = 65
    description = "Low visibility"
    threat_level = 0.5
    allowed_materials = 3 #1 for cloth, 2 for metal, 3 for both
    bonus = 2
    penalty = 2

[["armor"]]
    name = "plate boots"
    cell = 'boots'
    type = "armor"
    location = "Feet"
    base_value = 50
    description = "Sounds cool when you walk"
    threat_level = 0.5
    allowed_materials = 3 #1 for cloth, 2 for metal, 3 for both
    bonus = 1
    penalty = 1

[["armor"]]
    name = "plate bracers"
    cell = 'arms'
    type = "armor"
    location = "Arms"
    base_value = 50
    description = "Forearms look buff"
    threat_level = 0.5
    allowed_materials = 3 #1 for cloth, 2 for metal, 3 for both
    bonus = 1
    penalty = 1

[["armor"]]
    name = "death spaulders"
    cell = 'shoulder'
    type = "armor"
    location = "Shoulders"
    base_value = 40
    description = "Ironically, Looks better on the living"
    threat_level = 0.2
    allowed_materials = 3 #1 for cloth, 2 for metal, 3 for both
    bonus = 1
    penalty = 1

[["armor"]]
    name = "magic cloak"
    cell = 'cloak'
    type = "armor"
    location = "Cloak"
    base_value = 20
    description = "The name is rather misleading"
    threat_level = 0.1
    allowed_materials = 1 #1 for cloth, 2 for metal, 3 for both
    bonus = 1
    penalty = 1

[["armor"]]
    name = "endless ring"
    cell = 'ring'
    type = "armor"
    location = "Ring"
    base_value = 10
    description = "Feels like Pewter..."
    threat_level = 0.01
    allowed_materials = 2 #1 for cloth, 2 for metal, 3 for both
    bonus = 0
    penalty = 0

[["armor"]]
    name = "choker of destiny"
    cell = 'neck'
    type = "armor"
    location = "Neck"
    base_value = 50
    description = "Sad fate ahead"
    threat_level = 0.01
    allowed_materials = 3 #1 for cloth, 2 for metal, 3 for both
    bonus = 0
    penalty = 0