


[["consumable"]]
    name="light healing"
    cell='!'
    type="potion"
    min_effect=4 #min damage or turns the spell lasts
    max_effect=6
    max_stack=0 #unlimited stack size
    effect_type="heal" #spell to cast
    additional_effects="None" #additional effects like burning, freezing, slowing
    spell_effect="None" #graphical effect when item is used
    effect_color=[0, 0, 0] #use 0,0,0 for no color to the effect
    range=0 #range of spell, in cells
    radius=0 #how big of a radius of effects spells, like fireball
    max_targets=0 #0 for user/target, 1 for unlimited, or 2+ targets
    col=[255, 114, 114] #color of the item
    value=25 #gold value of this item
    stackable = true
    level = 0 #Used to restrict what classes can use this item. 0 = all/no restrictions, higher levels = higher restrictions

    
[["consumable"]]
    name="healing"
    cell='!'
    type="potion"
    min_effect=10
    max_effect=12
    max_stack=0
    effect_type="heal"
    additional_effects="None"
    spell_effect="None"
    effect_color=[0, 0, 0]
    range=0
    radius=0
    max_targets=0
    col=[255, 0, 0]
    value=50
    stackable = true
    level=3
    
[["consumable" ]]
    name="fireball"
    cell='#'
    type="scroll"
    min_effect=12
    max_effect=20
    max_stack=2
    effect_type="fireball"
    additional_effects="burn"
    spell_effect="explosion"
    effect_color=[0, 0, 0]
    range=80
    radius=3
    max_targets=1
    col=[255, 255, 0]
    value = 150
    stackable = true
    level = 3
    
[["consumable"]]
    name="chain lightning"
    cell='#'
    type="scroll"
    min_effect=10
    max_effect=20
    max_stack=3
    effect_type="chain lightning"
    additional_effects="None"
    spell_effect="beam"
    effect_color=[0, 0, 0]
    range=5
    radius=5
    max_targets=3
    col=[255, 255, 0]
    value=150
    stackable = true
    level = 3

[["consumable"]]
    name="lightning"
    cell='#'
    type="scroll"
    min_effect=20
    max_effect=30
    max_stack=3
    effect_type="lightning"
    additional_effects="None"
    spell_effect="beam"
    effect_color=[0, 0, 0]
    range=5
    radius=5
    max_targets=3
    col=[255, 255, 0]
    value=100
    stackable = true
    level = 2
    
[["consumable"]]
    name="confusion"
    cell='#'
    type="scroll"
    min_effect=10
    max_effect=12
    max_stack=3
    effect_type="confusion"
    additional_effects="None"
    spell_effect="None"
    effect_color=[0, 0, 0]
    range=8
    radius=0
    max_targets=1
    col=[255, 255, 0]
    value= 75
    stackable = true
    level = 2

[["consumable"]]
    name="minor light"
    cell='#'
    type="scroll"
    min_effect=0.5 # light value
    max_effect=0.75
    max_stack=3
    effect_type="light"
    additional_effects="None"
    spell_effect="None"
    effect_color=[255, 255, 255]
    range=50 # turns of light
    radius=0
    max_targets=1
    col=[155, 155, 155]
    value= 25
    stackable = true
    level = 1

[["consumable"]]
    name="light"
    cell='#'
    type="scroll"
    min_effect=0.75
    max_effect=1.0
    max_stack=3
    effect_type="light"
    additional_effects="None"
    spell_effect="None"
    effect_color=[255, 255, 255]
    range=100
    radius=0
    max_targets=1
    col=[200, 200, 200]
    value= 100
    stackable = true
    level = 2

[["consumable"]]
    name="major light"
    cell='#'
    type="scroll"
    min_effect=1.0
    max_effect=1.25
    max_stack=3
    effect_type="light"
    additional_effects="None"
    spell_effect="None"
    effect_color=[255, 255, 255]
    range=200
    radius=0
    max_targets=1
    col=[255, 255, 255]
    value= 225
    stackable = true
    level = 3

[["consumable"]]
    name="detect monsters"
    cell='#'
    type="scroll"
    min_effect=15
    max_effect=25
    max_stack=3
    effect_type="detect monster"
    additional_effects="None"
    spell_effect="None"
    effect_color=[255, 255, 255]
    range=200
    radius=0
    max_targets=1
    col=[255, 255, 255]
    value= 250
    stackable = true
    level = 2

[["consumable"]]
    name="detect items"
    cell='#'
    type="scroll"
    min_effect=15
    max_effect=25
    max_stack=3
    effect_type="detect items"
    additional_effects="None"
    spell_effect="None"
    effect_color=[255, 255, 255]
    range=200
    radius=0
    max_targets=1
    col=[255, 255, 255]
    value= 250
    stackable = true
    level = 2
