[["material"]]
    name = "Steel"
    price_mod = 3.0
    rarity = 1.0#0.03125
    type = 2 #1 for cloth, 2 for metal
    can_be_made_from = 3 # for weapons only, 2 armor only, 3 both
    description=""
    color=[159, 159, 159]
    armor_bonus = 3
    armor_penalty = 2
    weight = 2
    sharpness = 3
    durability = 4
    modifier = 5

[["material"]]
    name = "Iron"
    price_mod = 2.0
    rarity = 1.0#0.03125
    type = 2 #1 for cloth, 2 for metal
    can_be_made_from = 3 # for weapons only, 2 armor only, 3 both
    description=""
    color=[159, 159, 159]
    armor_bonus = 2
    armor_penalty = 2
    weight = 1
    sharpness = 2
    durability = 3
    modifier = 4

[["material"]]
    name = "Chocolate"
    price_mod = 8
    rarity = 1.0#0.03125
    type = 2 #1 for cloth, 2 for metal
    can_be_made_from = 3 # for weapons only, 2 armor only, 3 both
    description=""
    color=[159, 159, 159]
    armor_bonus = 6
    armor_penalty = 4
    weight = 3
    sharpness = 5
    durability = 7
    modifier = 6

[["material"]]
    name = "Obsidian"
    price_mod = 5.0
    rarity = 1.0#0.03125
    type = 2 #1 for cloth, 2 for metal
    can_be_made_from = 3 # for weapons only, 2 armor only, 3 both
    description=""
    color=[159, 159, 159]
    armor_bonus = 4
    armor_penalty = 2
    weight = 4
    sharpness = 4
    durability = 4
    modifier = 4

[["material"]]
    name = "Bronze"
    price_mod = 6.0
    rarity = 1.0#0.03125
    type = 2 #1 for cloth, 2 for metal
    can_be_made_from = 2 # for weapons only, 2 armor only, 3 both
    description=""
    color=[159, 159, 159]
    armor_bonus = 5
    armor_penalty = 4
    weight = 3
    sharpness = 5
    durability = 6
    modifier = 5