
#/*======================================================
#                    Base Weapons
#=======================================================*/
[["weapon"]]
    name="Great Sword"
    cell='/' #should keep weapons this character
    type="melee" #can be only melee for now, ranged will come later
    subtype="Great Sword"
    handed=2  #how many hands it takes to wield
    dual_wield=false  #can be dual wielded?
    damage_type="Straightsword"  #2x damage vs this protection type
    family = "straightsword" # the skill family this weapon belongs in
    base_value=100  #base value of the item before materials
    description=""  #Description of the item, not including material
    threat_level=0.5  #for calculating spawns, higher number = more dangerous
    size="tiny"
    damage = [2, 10, 1, 0] # min damage, max damage, mutliplier, bonus (2d10*1+0)
    accuracy = 0 #accuracy bonus or penalty

[["weapon"]]
    name="Berzerker"
    cell='/'
    type="melee"
    subtype="Great Sword"
    handed=1
    dual_wield=true
    damage_type="Straightsword"
    family = "straightsword"
    base_value=40
    description="You're making me crazy."
    threat_level=0.1
    size="tiny"
    damage = [4, 12, 1, 0] # min damage, max damage, mutliplier, bonus (2d10*1+0)
    accuracy = 0

[["weapon"]]
    name="Long Sword"
    cell='/'
    type="melee"
    subtype="Long Sword"
    handed=1
    dual_wield=false
    damage_type="Straightsword"
    family = "straightsword"
    base_value=60
    description="Standard Long Sword. Don't get too excited."
    threat_level=0.3
    size="tiny"
    damage = [2, 8, 1, 0] # min damage, max damage, mutliplier, bonus (2d10*1+0)
    accuracy = 1

[["weapon"]]
    name="Dagger"
    cell='/'
    type="melee"
    subtype="Dagger"
    handed=1
    dual_wield=true
    damage_type="Straightsword"
    family = "straightsword"
    base_value=40
    description="Tiny Dagger. +1 to opening canvas sacks."
    threat_level=0.1
    size="tiny"
    damage = [1, 3, 2, 1] # min damage, max damage, mutliplier, bonus (2d10*1+0)
    accuracy = 2

[["weapon"]]
    name="Tower Shield"
    cell='/'
    type="melee"
    subtype="Shield"
    handed=1
    dual_wield=false
    damage_type="Straightsword"
    family = "straightsword"
    base_value=40
    description="Not as tall as the name implies"
    threat_level=0.1
    size="tiny"
    damage = [0, 0, 0, 0] # min damage, max damage, mutliplier, bonus (2d10*1+0)
    accuracy = 2

[["weapon"]]
    name="Medium Buckler"
    cell='/'
    type="melee"
    subtype="Shield"
    handed=1
    dual_wield=true
    damage_type="Straightsword"
    family = "straightsword"
    base_value=40
    description="Little guys may call it a Large Buckler"
    threat_level=0.1
    size="tiny"
    damage = [0, 0, 0, 0] # min damage, max damage, mutliplier, bonus (2d10*1+0)
    accuracy = 2
